<a href="https://colab.research.google.com/github/AsfiyaFirdouse/Deep-Learning/blob/main/Social_Media.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/drive/MyDrive/Social Media Usage and Emotional Well-Being.csv")
df

User_ID  Age      Gender   Platform  Daily_Usage_Time (minutes)  \
0          1   25      Female  Instagram                         120   
1          2   30        Male    Twitter                          90   
2          3   22  Non-binary   Facebook                          60   
3          4   28      Female  Instagram                         200   
4          5   33        Male   LinkedIn                          45   
..       ...  ...         ...        ...                         ...   
995      996   33  Non-binary    Twitter                          85   
996      997   22      Female   Facebook                          70   
997      998   35        Male   Whatsapp                         110   
998      999   28  Non-binary   Telegram                          60   
999     1000   27      Female   Snapchat                         120   

     Posts_Per_Day  Likes_Received_Per_Day  Comments_Received_Per_Day  \
0                3                      45                         10   
1                5                      20                         25   
2                2                      15                          5   
3                8                     100                         30   
4                1                       5                          2   
..             ...                     ...                        ...   
995              4                      35                         18   
996              1                      14                          6   
997              3                      50                         25   
998              2                      18                          8   
999              4                      40                         18   

     Messages_Sent_Per_Day Dominant_Emotion  
0                       12        Happiness  
1                       30            Anger  
2                       20          Neutral  
3                       50          Anxiety  
4                       10          Boredom  
..                     ...              ...  
995                     18          Boredom  
996                     10          Neutral  
997                     25        Happiness  
998                     18            Anger  
999                     22          Neutral  

[1000 rows x 10 columns]

In [ ]:
pd.to_numeric(df['Age'], downcast='integer')
df

User_ID  Age      Gender   Platform  Daily_Usage_Time (minutes)  \
0          1   25      Female  Instagram                         120   
1          2   30        Male    Twitter                          90   
2          3   22  Non-binary   Facebook                          60   
3          4   28      Female  Instagram                         200   
4          5   33        Male   LinkedIn                          45   
..       ...  ...         ...        ...                         ...   
995      996   33  Non-binary    Twitter                          85   
996      997   22      Female   Facebook                          70   
997      998   35        Male   Whatsapp                         110   
998      999   28  Non-binary   Telegram                          60   
999     1000   27      Female   Snapchat                         120   

     Posts_Per_Day  Likes_Received_Per_Day  Comments_Received_Per_Day  \
0                3                      45                         10   
1                5                      20                         25   
2                2                      15                          5   
3                8                     100                         30   
4                1                       5                          2   
..             ...                     ...                        ...   
995              4                      35                         18   
996              1                      14                          6   
997              3                      50                         25   
998              2                      18                          8   
999              4                      40                         18   

     Messages_Sent_Per_Day Dominant_Emotion  
0                       12        Happiness  
1                       30            Anger  
2                       20          Neutral  
3                       50          Anxiety  
4                       10          Boredom  
..                     ...              ...  
995                     18          Boredom  
996                     10          Neutral  
997                     25        Happiness  
998                     18            Anger  
999                     22          Neutral  

[1000 rows x 10 columns]

In [ ]:
df=df.drop('User_ID',axis=1)
df

Age      Gender   Platform  Daily_Usage_Time (minutes)  Posts_Per_Day  \
0     25      Female  Instagram                         120              3   
1     30        Male    Twitter                          90              5   
2     22  Non-binary   Facebook                          60              2   
3     28      Female  Instagram                         200              8   
4     33        Male   LinkedIn                          45              1   
..   ...         ...        ...                         ...            ...   
995   33  Non-binary    Twitter                          85              4   
996   22      Female   Facebook                          70              1   
997   35        Male   Whatsapp                         110              3   
998   28  Non-binary   Telegram                          60              2   
999   27      Female   Snapchat                         120              4   

     Likes_Received_Per_Day  Comments_Received_Per_Day  Messages_Sent_Per_Day  \
0                        45                         10                     12   
1                        20                         25                     30   
2                        15                          5                     20   
3                       100                         30                     50   
4                         5                          2                     10   
..                      ...                        ...                    ...   
995                      35                         18                     18   
996                      14                          6                     10   
997                      50                         25                     25   
998                      18                          8                     18   
999                      40                         18                     22   

    Dominant_Emotion  
0          Happiness  
1              Anger  
2            Neutral  
3            Anxiety  
4            Boredom  
..               ...  
995          Boredom  
996          Neutral  
997        Happiness  
998            Anger  
999          Neutral  

[1000 rows x 9 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
col=['Gender','Platform','Dominant_Emotion']
for col_name in col:
  df[col_name]=le.fit_transform(df[col_name])
df

Age  Gender  Platform  Daily_Usage_Time (minutes)  Posts_Per_Day  \
0     25       0         1                         120              3   
1     30       1         5                          90              5   
2     22       2         0                          60              2   
3     28       0         1                         200              8   
4     33       1         2                          45              1   
..   ...     ...       ...                         ...            ...   
995   33       2         5                          85              4   
996   22       0         0                          70              1   
997   35       1         6                         110              3   
998   28       2         4                          60              2   
999   27       0         3                         120              4   

     Likes_Received_Per_Day  Comments_Received_Per_Day  Messages_Sent_Per_Day  \
0                        45                         10                     12   
1                        20                         25                     30   
2                        15                          5                     20   
3                       100                         30                     50   
4                         5                          2                     10   
..                      ...                        ...                    ...   
995                      35                         18                     18   
996                      14                          6                     10   
997                      50                         25                     25   
998                      18                          8                     18   
999                      40                         18                     22   

     Dominant_Emotion  
0                   3  
1                   0  
2                   4  
3                   1  
4                   2  
..                ...  
995                 2  
996                 4  
997                 3  
998                 0  
999                 4  

[1000 rows x 9 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         1000 non-null   int64
 1   Gender                      1000 non-null   int64
 2   Platform                    1000 non-null   int64
 3   Daily_Usage_Time (minutes)  1000 non-null   int64
 4   Posts_Per_Day               1000 non-null   int64
 5   Likes_Received_Per_Day      1000 non-null   int64
 6   Comments_Received_Per_Day   1000 non-null   int64
 7   Messages_Sent_Per_Day       1000 non-null   int64
 8   Dominant_Emotion            1000 non-null   int64
dtypes: int64(9)
memory usage: 70.4 KB


In [ ]:
X = df.drop('Dominant_Emotion',axis=1)
y = df['Dominant_Emotion']
y=np.array(df['Dominant_Emotion'])

from tensorflow.keras.utils import to_categorical

y=to_categorical(y)
y


array([[0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       ...,
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)

In [ ]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
x_scale= min_max_scaler.fit_transform(X)
print(x_scale)

[[0.28571429 0.         0.16666667 ... 0.38095238 0.21052632 0.0952381 ]
 [0.64285714 0.5        0.83333333 ... 0.14285714 0.60526316 0.52380952]
 [0.07142857 1.         0.         ... 0.0952381  0.07894737 0.28571429]
 ...
 [1.         0.5        1.         ... 0.42857143 0.60526316 0.4047619 ]
 [0.5        1.         0.66666667 ... 0.12380952 0.15789474 0.23809524]
 [0.42857143 0.         0.5        ... 0.33333333 0.42105263 0.33333333]]


In [ ]:
# Splitting training and test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x_scale,y,test_size=0.20,random_state=0)

In [ ]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import LeakyReLU
from keras.layers import Dense
from tensorflow.keras.layers import Dropout

model=Sequential()
model.add(Dense(50, activation='relu', input_shape=(8,)))
model.add(Dense(42, activation='relu'))
model.add(Dropout(0.12))
model.add(Dense(30, activation=LeakyReLU(alpha=0.01)))
#output layer
model.add(Dense(6, activation='softmax'))
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=10, epochs=250)

Epoch 1/250
80/80 [==============================] - 1s 2ms/step - loss: 1.7010 - accuracy: 0.2812
Epoch 2/250
80/80 [==============================] - 0s 2ms/step - loss: 1.5043 - accuracy: 0.4512
Epoch 3/250
80/80 [==============================] - 0s 2ms/step - loss: 1.3649 - accuracy: 0.5000
Epoch 4/250
80/80 [==============================] - 0s 2ms/step - loss: 1.2953 - accuracy: 0.5088
Epoch 5/250
80/80 [==============================] - 0s 2ms/step - loss: 1.2538 - accuracy: 0.5412
Epoch 6/250
80/80 [==============================] - 0s 2ms/step - loss: 1.2378 - accuracy: 0.5337
Epoch 7/250
80/80 [==============================] - 0s 3ms/step - loss: 1.1965 - accuracy: 0.5500
Epoch 8/250
80/80 [==============================] - 0s 2ms/step - loss: 1.1618 - accuracy: 0.5763
Epoch 9/250
80/80 [==============================] - 0s 2ms/step - loss: 1.1348 - accuracy: 0.5775
Epoch 10/250
80/80 [==============================] - 0s 3ms/step - loss: 1.1290 - accuracy: 0.5713
Epoch 11/

In [ ]:
y_pred=model.predict(X_test)
y_pred
y_pred = np.argmax(y_pred, axis=1) + 1
y_pred
np.column_stack((y_pred, y_test))

7/7 [==============================] - 0s 2ms/step


array([[6., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 1., 0.],
       [6., 0., 0., ..., 0., 0., 1.],
       [4., 0., 0., ..., 1., 0., 0.]])

In [ ]:
from sklearn.metrics import accuracy_score

loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test Loss:', loss)
print('Test Accuracy:', accuracy)

Test Loss: 0.05388405919075012
Test Accuracy: 0.9900000095367432
